{
 "title": "Kubernetes Alert",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Alert List", "type": "alertlist", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Kubernetes Node Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_node_status_ready{condition=\"true\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (hostname) (irate(node_cpu{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((node_memory_MemTotal - node_memory_MemFree - node_memory_Buffers - node_memory_Cached) / node_memory_MemTotal) * 100",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Node Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_size - node_filesystem_avail) by (hostname) / sum(node_filesystem_size) by (hostname) * 100",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "[ default ] Deployment Replica Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "min(kube_deployment_status_replicas_available{namespace=\"default\"}) without (instance, pod) / max(kube_deployment_spec_replicas{namespace=\"default\"}) without (instance, pod) * 100",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "[ monitoring ] Deployment Replica Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "min(kube_deployment_status_replicas_available{namespace=\"monitoring\"}) without (instance, pod) / max(kube_deployment_spec_replicas{namespace=\"monitoring\"}) without (instance, pod) * 100",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "[ kube-system ] Deployment Replica Percentage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "min(kube_deployment_status_replicas_available{namespace=\"kube-system\"}) without (instance, pod) / max(kube_deployment_spec_replicas{namespace=\"kube-system\"}) without (instance, pod) * 100",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "[ rundeck ] Deployment Replica Percentage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "min(kube_deployment_status_replicas_available{namespace=\"rundeck\"}) without(instance, pod) / max(kube_deployment_spec_replicas{namespace=\"rundeck\"}) without (instance, pod) * 100",
     "legendFormat": "{{deployment}}"
    }
   ]
  }
 ]
}