{
 "title": "Kubernetes Node",
 "description": "Dashboard to get an overview of one kubernetes node",
 "tags": [ "prometheus" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "query": "label_values(hostname)" }
  ]
 },
 "panels": [
  {
   "title": "Idle cpu",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu{mode=\"idle\", hostname=\"$server\"}[5m])) * 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load1{hostname=\"$server\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{hostname=\"$server\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{hostname=\"$server\"}",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{hostname=\"$server\"} - node_memory_MemFree{hostname=\"$server\"} - node_memory_Buffers{hostname=\"$server\"} - node_memory_Cached{hostname=\"$server\"}",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers{hostname=\"$server\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached{hostname=\"$server\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree{hostname=\"$server\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((node_memory_MemTotal{hostname=\"$server\"} - node_memory_MemFree{hostname=\"$server\"}  - node_memory_Buffers{hostname=\"$server\"} - node_memory_Cached{hostname=\"$server\"}) / node_memory_MemTotal{hostname=\"$server\"}) * 100"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (hostname) (rate(node_disk_bytes_read{hostname=\"$server\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum by (hostname) (rate(node_disk_bytes_written{hostname=\"$server\"}[2m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum by (hostname) (rate(node_disk_io_time_ms{hostname=\"$server\"}[2m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size{device!=\"rootfs\",hostname=\"$server\"}) - sum(node_filesystem_free{device!=\"rootfs\",hostname=\"$server\"})) / sum(node_filesystem_size{device!=\"rootfs\",hostname=\"$server\"})"
    }
   ]
  },
  {
   "title": "Network received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes{hostname=\"$server\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes{hostname=\"$server\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}