{
 "title": "Kubernetes Resource",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU request",
   "type": "table",
   "gridPos": { "h": 33, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{namespace=\"default\"}) by (container)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "table",
   "gridPos": { "h": 33, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "avg (rate (container_cpu_usage_seconds_total{namespace=\"default\",container_name!=\"logger\",container_name!=\"POD\"}[1m])) by (container_name) * 100 / 16"
    }
   ]
  },
  {
   "title": "CPU limit",
   "type": "table",
   "gridPos": { "h": 33, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace=\"default\"}) by (container)"
    }
   ]
  },
  {
   "title": "Memory request",
   "type": "table",
   "gridPos": { "h": 33, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{namespace=\"default\"}) by (container) /1024/1024/1024"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "table",
   "gridPos": { "h": 33, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{namespace=\"default\",container_name!=\"POD\",container_name!=\"logger\"}) by (container_name) /1024/1024/1024"
    }
   ]
  },
  {
   "title": "Memory limit",
   "type": "table",
   "gridPos": { "h": 33, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace=\"default\"}) by (container) /1024/1024/1024"
    }
   ]
  }
 ]
}